### ISSUE TITLE
when can we have flink1.11, thx?

### ISSUE THREAD

**Issue by sun-biao** [aws-samples/streaming-analytics-workshop#21]

**Comment by sthm** [comment]
Hey @sun-biao, thanks for reaching out. We are currently in the process of adding new content and will update the workshop to Flink 1.11 as part of these updates. The changes have already been rolled out to the website and will be reflected in the repo at some later point.

**Comment by sthm** [comment]
Website and sources on GitHub have been updated now. Please let us know what you think!
