### ISSUE TITLE
CloudFormation fails

### ISSUE THREAD

**Issue by tsugunao** [aws-samples/streaming-analytics-workshop#28]
When I tried to do this workshop, I found that the Cloud Formation fails.
The reason it fails is that the url path of github archived resource is not valid.
KinesisReplayBuildPipelineDownloadLambda3BF1DB4C -> "url": "https://github.com/aws-samples/amazon-kinesis-replay/archive/release-0.1.0.zip"

ConsumerApplicationBuildPipelineDownloadLambda1685DE7F -> "url": "https://github.com/aws-samples/amazon-kinesis-analytics-taxi-consumer/archive/release-0.2.1.zip"

If we change the url to "https://github.com/aws-samples/amazon-kinesis-replay/archive/refs/tags/release-0.1.0.zip" or 
https://github.com/aws-samples/amazon-kinesis-analytics-taxi-consumer/archive/refs/tags/release-0.2.1.zip", it will succeed

**Comment by sthm** [comment]
Thank you for your patience! Apparently the way downloading archives from GitHub changed. I've changed the URLs as described and push the changes to all relevant sites. Thanks a lot!
